import React, { useEffect, useRef, useState, useCallback } from 'react';
import { useParams, useLocation, useNavigate } from 'react-router-dom';
import api from '../api/axios';

export default function QuizAttempt() {
  const { id } = useParams(); const location = useLocation(); const navigate = useNavigate(); const attemptId = location.state?.attemptId;
  const [quiz, setQuiz] = useState(null); const [questions, setQuestions] = useState([]); const [current, setCurrent] = useState(0); const [answers, setAnswers] = useState({}); const [secondsLeft, setSecondsLeft] = useState(null); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(''); const submittedRef = useRef(false);
  useEffect(() => { if (!attemptId) { navigate(`/quizzes/${id}`); return; } Promise.all([api.get(`/quizzes/${id}`), api.get(`/quizzes/${id}/questions`)]).then(([quizRes, qRes]) => { setQuiz(quizRes.data); setQuestions(qRes.data); setSecondsLeft(quizRes.data.duration_minutes * 60); }).catch((err) => setError(err.response?.data?.message || 'Could not load the quiz. Make sure the backend is running on port 5001.')); }, [id, attemptId, navigate]);
  const handleSubmit = useCallback(async () => { if (submittedRef.current) return; submittedRef.current = true; setSubmitting(true); const payload = { attempt_id: attemptId, answers: Object.entries(answers).map(([question_id, selected_option_id]) => ({ question_id: Number(question_id), selected_option_id: Number(selected_option_id) })) }; try { const { data } = await api.post(`/quizzes/${id}/submit`, payload); navigate(`/results/${data.id}`); } catch (err) { alert(err.response?.data?.message || 'Submission failed'); submittedRef.current = false; setSubmitting(false); } }, [answers, attemptId, id, navigate]);
  useEffect(() => { if (secondsLeft === null) return; if (secondsLeft <= 0) { handleSubmit(); return; } const timer = setInterval(() => setSecondsLeft((s) => s - 1), 1000); return () => clearInterval(timer); }, [secondsLeft, handleSubmit]);
  if (!quiz || questions.length === 0) return <div className="empty-state" style={{ width: 'min(500px, calc(100% - 40px))', margin: '70px auto' }}>{error || 'Loading challenge...'}</div>;
  const q = questions[current]; const minutes = Math.floor(secondsLeft / 60); const seconds = secondsLeft % 60;
  function selectOption(optionId) { setAnswers((prev) => ({ ...prev, [q.id]: optionId })); }
  return <main className="page-narrow"><div className="quiz-topbar"><div><p className="eyebrow">Focus mode</p><h1 className="section-title">{quiz.title}</h1></div><span className={`timer ${secondsLeft < 60 ? 'warning' : ''}`}>◷ {String(minutes).padStart(2, '0')}:{String(seconds).padStart(2, '0')}</span></div><div className="progress-track" style={{ marginBottom: 18 }}><div className="progress-fill" style={{ width: `${((current + 1) / questions.length) * 100}%` }} /></div><section className="question-card"><div className="question-kicker"><span>Question {current + 1} of {questions.length}</span><span>{answers[q.id] ? 'Answer saved' : 'Choose one answer'}</span></div><h2>{q.question_text}</h2><div style={{ display: 'grid', gap: 10 }}>{q.options.map((opt, index) => <button type="button" key={opt.id} onClick={() => selectOption(opt.id)} className={`option-card ${answers[q.id] === opt.id ? 'selected' : ''}`}><span className="option-letter">{String.fromCharCode(65 + index)}</span><span>{opt.option_text}</span></button>)}</div></section><div className="question-nav"><button disabled={current === 0} onClick={() => setCurrent((c) => c - 1)} className="btn-secondary">← Previous</button><div className="number-nav">{questions.map((qq, idx) => <button key={qq.id} onClick={() => setCurrent(idx)} className={`${idx === current ? 'current' : ''} ${answers[qq.id] && idx !== current ? 'answered' : ''}`}>{idx + 1}</button>)}</div>{current < questions.length - 1 ? <button onClick={() => setCurrent((c) => c + 1)} className="btn-primary">Next →</button> : <button onClick={handleSubmit} disabled={submitting} className="btn-coral">{submitting ? 'Submitting...' : 'Finish quiz ✓'}</button>}</div></main>;
}
